### ISSUE TITLE
Deprecation warning on process.EventEmitter

### ISSUE THREAD

**Issue by theHazzard** [mafintosh/sqs#30]
Node 6 is logging some deprecation warnings when using process.EventEmitter.
on this line: [index.js:120](https://github.com/mafintosh/sqs/blob/master/index.js#L120)

I don't think this will break soon, but though it would be nice to inform this.

**Comment by theHazzard** [comment]
this is the deprecation warning.

DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

**Comment by mafintosh** [comment]
should be fixed in 1.4.1

**Comment by theHazzard** [comment]
Thanks!!
